export enum DrawType {
    FILL_ROTATED_QUAD = 1,
    DRAW_ROTATED_QUAD = 2,
    FILL_LINED_ROTATED_QUAD = 3,

    FILL_AA_QUAD = 4,
    DRAW_AA_QUAD = 5,
    FILL_LINED_AA_QUAD = 6,

    FILL_ELLIPSOID = 7,
    DRAW_ELLIPSOID = 8,
    FILL_LINED_ELLIPSOID = 9,

    FILL_CIRCLE = 10,
    DRAW_CIRCLE = 11,
    FILL_LINED_CIRCLE = 12,
}